const texts = {
    ar: {
        about: 'عن الجمعية',
        aboutAssociation: 'نبذة عن الجمعية',
        aboutAssociationContent: '',
        chairmanWord: 'كلمة رئيس مجلس الإدارة',
        chairmanWordContent: '',
        generalAssociation: 'الجمعية العمومية',
        generalAssociationMembers: 'أعضاء الجمعية العمومية',
        generalAssociationMembersContent: '',
        generalAssociationDecisions: 'قرارات الجمعية العمومية',
        generalAssociationDecisionsContent: '',
        organizationalStructure: 'الهيكل التنظيمي',
        organizationalStructureContent: '',
        boardDirectors: 'مجلس الادارة',
        boardDirectorsContent: '',
        executiveCommittee: 'اللجنة التنفيذية',
        executiveCommitteeContent: '',
        investmentCommitte: 'لجنة الاستثمار',
        investmentCommitteContent: '',
        planingDevelopmentCommitte: 'لجنة التخطيط والتطوير',
        planingDevelopmentCommitteContent: '',
        policyGovernanceReviewCommittee: 'لجنة التدقيق و المراجعةالداخلية و الحوكمة',
        policyGovernanceReviewCommitteeContent: '',
        internalAuditReviewCommittee: 'اللجنة الاجتماعية',
        internalAuditReviewCommitteeContent: '',
        services: 'الخدمات الإلكترونية',
        voluntare: 'التطوع',
        voluntareContent: '',
        awarenessCornerRequest: 'طلب شراكة مجتمعية',
        awarenessCornerRequestContent: '',
        awarenessLectureRequest: 'طلب محاضرة توعوية',
        awarenessLectureRequestContent: '',
        membership: 'العضوية',
        aboutMembership: 'نبذة عن العضوية',
        aboutMembershipContent: '',
        associationRegister: 'الاشتراك بالجمعية',
        associationRegisterContent: '',
        associationCard: 'بطاقة العضوية',
        associationCardContent: '',
        ourPrograms: 'برامجنا',
        news: 'الأخبار',
        library: 'المكتبة',
        images: 'الصور',
        videos: 'الفيديوهات',
        reports: 'التقارير',
        systemsRegulations: 'الأنظمة واللوائح',
        systemsRegulationsContent: '',
        callUs: 'اتصل بنا',
        donate: 'تبرع',
        post: 'اتفاقية تعاون بين الجمعية و جامعة معرفة',
        latestNews: 'اخر الاخبار',
        mainMenu: 'القائمة الرئيسية',
        lang: 'English',
        mainPage: 'الصفحة الرئيسية',
        identity: 'جمعية الوقاية من العنف و الايذاء و التشرد © 2022',
        conflictPolicy: 'سياسة تعارض المصالح',
        whistleblowingPolicy: 'سياسة الإبلاغ عن المخالفات',
        organizingRelationshipWithBeneficiaries: 'سياسة تنظيم العلاقات مع المستفيدين',
        fundraisingPolicy: 'سياسة جمع التبرعات',
        dataPrivacyPolicy: 'سياسة خصوصية البيانات',
        documentRetentionPolicy: 'سياسة ا لإحتفاظ بالوثائق',
        antiTerroristFinancingPolicy: 'سياسة مكافحة تمويل الإرهاب',
        volunteerManagementMechanism: 'آلية ادارة المتطوعين',
        mechanismToVerifyTheBeneficiaries: 'آلية التحقق من استحقاق المستفيد',
        messages: 'الرسائل',
        suggestions: 'الإقتراحات و الشكاوى',
    },
    en: {
        about: 'About the Association',
        aboutAssociation: 'About the Association',
        aboutAssociationContent: '',
        chairmanWord: 'Chairman’s Word',
        chairmanWordContent: '',
        generalAssociation: 'General Association',
        generalAssociationMembers: 'General Association Members',
        generalAssociationMembersContent: '',
        generalAssociationDecisions: 'General Association Desisions',
        generalAssociationDecisionsContent: '',
        organizationalStructure: 'Organizational Structure',
        organizationalStructureContent: '',
        boardDirectors: 'Board Directors',
        boardDirectorsContent: '',
        executiveCommittee: 'Excutive Committee',
        executiveCommitteeContent: '',
        investmentCommitte: 'Investment Committee',
        investmentCommitteContent: '',
        planingDevelopmentCommitte: 'Planing and Development Committee',
        planingDevelopmentCommitteContent: '',
        policyGovernanceReviewCommittee: 'Internal Audit Review and Governance Committee',
        policyGovernanceReviewCommitteeContent: '',
        internalAuditReviewCommittee: 'Social Committee',
        internalAuditReviewCommitteeContent: '',
        services: 'Services',
        voluntare: 'Voluntare',
        voluntareContent: '',
        awarenessCornerRequest: 'Awareness Corner Request',
        awarenessCornerRequestContent: '',
        awarenessLectureRequest: 'Awareness Lecture Request',
        awarenessLectureRequestContent: '',
        membership: 'Membership',
        aboutMembership: 'About Membership',
        aboutMembershipContent: '',
        associationRegister: 'Association Register',
        associationRegisterContent: '',
        associationCard: 'Association Card',
        associationCardContent: '',
        ourPrograms: 'Our Programs',
        news: 'News',
        library: 'Library',
        images: 'Images',
        videos: 'Videos',
        reports: 'Reports',
        systemsRegulations: 'System Regulations',
        systemsRegulationsContent: '',
        callUs: 'Call Us',
        donate: 'Donate',
        post: 'Cooperation agreement between the association and the University of Knowledge',
        latestNews: 'Latest News',
        mainMenu: 'Main Menu',
        lang: 'عربي',
        mainPage: 'Main Page',
        identity: 'Violence, Abuse and Homelessness Prevention Association © 2022',
        conflictPolicy: 'Conflict of interest policy',
        whistleblowingPolicy: 'Whistleblowing Policy',
        organizingRelationshipWithBeneficiaries: 'organizing the Relationship with Beneficiaries',
        fundraisingPolicy: 'Fundraising Policy',
        dataPrivacyPolicy: 'Data Privacy Policy',
        documentRetentionPolicy: 'Document Retention Policy',
        antiTerroristFinancingPolicy: 'Anti-Terrorist Financing Policy',
        volunteerManagementMechanism: 'Volunteer Management Mechanism',
        mechanismToVerifyTheBeneficiaries: 'Mechanism To Verify The Beneficiaries',
        messages: 'Messages',
        suggestions: 'Suggestions and Complaints',
    },
}
export default texts;