const texts = {
    en: {
        lang: 'عربي',
        contact: 'Contact us',
        terms: 'Terms and Conditions',
        policy: 'Usage policy',
        welcome: 'Welcome ',
        fastSteps: 'Quick steps and your account will be ready',
        changeImg: 'change image',
        recommendedImgSize: 'Recommended image size',
        country: 'Country',
        saudi: 'Saudi arabia',
        city: 'City',
        jed: 'Jeddah',
        ryd: 'Riyadh',
        teacherType: 'Teacher type',
        academy: 'Academy',
        profession: 'Profession',
        bio: 'Biography',
        allowedBio: 'Maximum 300 letters, Minimum 200 letters.',
        skip: 'Skip',
        next: 'Next',
        previos: 'Previos',
        accountSetting: 'Account setting',
        firstStep: 'First step',
        secondStep: 'Second step',
        thirdStep: 'Third step',
        finalStep: 'Final step',
        basicInfo: 'Basic information',
        studyAndCertificate: 'Study and Certificates',
        teachingSpecification: 'Teaching Specifications',
        availableTime: 'Available time',
        havingChallenges: 'Having challenges ?',
        contactUs: 'Contact us for help',
        bachelor: 'Bachelor',
        diploma: 'Diploma',
        certificate: 'University certificate',
        arabic: 'Arabic',
        english: 'English',
        engineer: 'Engineer',
        science: 'Science',
        physics: 'Physics',
        algebra: 'Algebra',
        specialization: 'Specialty',
        experience: 'Years of experiance',
        fromOneToThreeYears: 'From 1 to 3 years',
        fromThreeToFiveYears: 'From 3 to 5 years',
        certificatesYouGot: 'Certificates that you have',
        delete: 'Delete',
        certificateImg: 'Certificate image',
        chooseFromDevice: 'Choose from device',
        teachingTypes: 'Teaching types',
        remote: 'Remote',
        attend: 'Attend',
        sr: 'SR',
        hourPrice: 'Hour price',
        makeOnZoom: 'Make on Zoom',
        chooseAttendPlace: 'choose the place by agreement',
        studentType: 'Type of students you want to teach',
        studentStage: 'Students stage you want to teach',
        male: 'Male',
        female: 'Female',
        intermedate: 'Intermediate',
        highschool: 'High School',
        university: 'Uinversity',
        search: 'Search',
        subjectsYouTeach: 'Subjects that you teach',
        arabic: "Arabic",
        english: "English",
        engineer: "Engineer",
        science: "Science",
        physics: "Physics",
        math: "Math",
        reservationType: 'Reservation type',
        reservationByMassaging: 'Reservation by massaging',
        reservationBySchedule: 'Reservation immediatly',
        dateSelectionByMassaging: 'Date selection is done by chatting with students',
        dateSelectionBySchedule: 'Date selection is done by choosing from schedule',
        personalSchedule: 'Personal schedule',
        edit: 'Edit',
        saturday: 'Saturday',
        sunday: 'Sunday',
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        unavailable: 'Unavailable',
        am: 'AM',
        pm: 'PM',
        to: 'To',
        from: 'From',
        selectAvailableTime: 'Select available time',
        save: 'Save',
        thanksOrderRecieved: 'Thanks, your order is recieved',
        administrationWillContactYou: 'The administration will contact you within 48 hours',
        accept: 'Accept',
        close: 'Close',
        main: 'Main',
        dates: 'Dates',
        massages: 'Massages',
        development: 'Development courses',
        freeLessons: 'Free lessons',
        savings: 'Wallet and savings',
        settings: 'Settings',
        signout: 'Sign out',
        signin: 'Sign in',
        signup: 'Sign up',
        customAccount: 'Custom account',
        totalBalance: 'Total balance',
        moneyTransactions: 'Money transactions',
        nextAppointment: 'Next appointment',
        minutes: 'Minuets',
        hours: 'Hours',
        days: 'days',
        lessonLink: 'Lesson link',
        quickLinks: 'Quick links',
        howYourFileShow: 'How your file shows',
        inviteFriends: 'Invite friends',
        enterCode: 'Enter discount code',
        technicalSupport: 'Whats app technical support',
        dontHaveAccount: 'Dont have an account?',
        newAccount: 'New account',
        forgetPassword: 'Forget password',
        phoneNumber: 'Phone number',
        password: 'Password',
        nameWarning: 'Must enter a name *',
        phoneWarning: 'Use nine numbers only *',
        emailWarning: 'Invalid email *',
        genderWarning: 'Must select from the choices *',
        passwordWarning: 'Use eight or more letters contains small, capital and special character *',
        termsWarning: 'Must accept terms and conditions *',
        name: 'Name',
        email: 'Email',
        acceptTerms: 'Accept',
        men: 'Male',
        women: 'Female',
        teachingHours: 'Teaching hours',
        studentsTeached: 'Students you teached',
        profileViews: 'Profile views',
        march: 'March',
        today: 'Today',
        weakly: 'Weakly',
        monthly: 'Monthly',
        privateLesson: 'Private lesson',
        developmentCourse: 'Developmant course',
        mohamedAbdullrabman: 'Mohamed abdullrahman',
        improveSearchEngines: 'Improve search engines',
        abdullrahmanKhatry: 'Abdullarahman khatry',
        filter: 'Filter',
        studentOneName: 'Ahmed shawqy',
        studentTwoName: 'Abdullrahman mohamed',
        studentThreeName: 'Marwa mohamed amer',
        studentFourName: 'Mosfer althobaity',
        studentFiveName: 'Abdullmajed alkheer',
        dateOne: 'Friday 30 december 2022-09:00',
        dateTwo: 'Thursday 27 may 2022-12:15',
        dateThree: 'Sunday 12 december 2022-04:30',
        dateFour: 'Friday 30 december 2022-06:30',
        dateFive: 'Monday 19 december 2022-10:00',
        coming: 'coming',
        active: 'active',
        done: 'done',
        cancel: 'cancel',
        dateDetails: 'Date details',
        reservationDetails: 'Reservation details',
        dateState: 'State',
        lessonDate: 'Lesson date',
        reservationHours: 'Reservation hours',
        lessonTime: 'LessonTime',
        lessonLocation: 'Lesson location',
        week: 'Week',
        minute: 'Minutes',
        reciept: 'Reciept',
        price: 'Price',
        additionalVat: 'Additional vat',
        totalPrice: 'Total price',
        massageStudent: 'Massage student',
        apply: 'Apply',
        chating: 'Chating',
        selectDate: 'Select date',
        send: 'Send',
        massageText: 'Massage text',
        startMakingCourses: 'Start making courses in different subjects by opening live a with your students',
        addCourse: 'Add course',
        courseTime: 'Course time',
        courseLocation: 'Course location',
        startDate: 'Start date',
        courseName: 'Course name',
        courseHours: 'Course hours',
        topics: 'Topics',
        add: 'Add',
        shareCourse: 'Share course',
        suggestionsList:'Suggestions list for course place',
        deleteLocation: 'Delete location',
        yon: 'Yonboa',
        tif: 'Taif',
        jedDiscription: 'Jeddah - Kornaish',
        rydDiscription: 'Riyadh - King road',
        yonDiscription: 'Yonboa - Park',
        tifDiscription: 'Taif - Alhada',
        showOnMap: 'Show on map',
        freeLessonsIncreaseYourExplore: 'Free lessons increase your explore',
        addFreeLesson: 'Add free lesson',
        allowedNumber: 'Allowed',
        reservedNumber: 'Reservation',
        student: 'Student',
        lessonTopic: 'Lesson topic',
        maxStudent: 'Maximum number of students',
        addLesson: 'Add lesson',
        lessonHour: 'Lesson time',
        shareLesson: 'Share lesson',
        transactionsEveryMonth: 'Salary is sent in the begining of each month',
        holdBalance: 'Hold balance',
        availableBalance: 'Available balance',
        addBankAccount: 'Add bank account to recieve salary',
        ifDontHaveAccount: 'If you dont have an account contact managment to recieve salary',
        totalTransactions: 'Total transactions',
        usuallyTakesTwoDays: 'Operation usually takes 2 days to be shown here',
        alahly: 'Alahly',
        alrajhy: 'Alrajhy',
        albalad: 'Albelad',
        alarabi: 'Alarabi',
        chooseBankName: 'Choose bank name',
        transferToYou: 'Transfer to you',
        addAccountToRecieveSalary: 'Enter account details to recieve salary',
        accountOwnerName: 'Account owner name',
        accountNumber: 'Account number',
        ipanNumber: 'Ipan number',
    },




    ar: {
        lang: 'English',
        contact: 'تواصل معنا',
        terms: 'الشروط و الاحكام',
        policy: 'سياسة الاستخدام',
        welcome: 'مرحبا بك-استاذ ',
        fastSteps: 'خطوات سريعه و يصبح حسابك مكتمل',
        changeImg: 'تغيير الصوره',
        recommendedImgSize: 'يوصى بمقاس الصوره',
        country: 'الدولة',
        saudi: 'المملكه العربيه السعوديه',
        city: 'المدينة',
        jed: 'جدة',
        ryd: 'الرياض',
        teacherType: 'نوع المدرس',
        academy: 'أكاديمي',
        profession: 'مهني',
        bio: 'نبذة تعريفية',
        allowedBio: 'متاح استخدام 300 حرف - اقل حد 200 حرف',
        skip: 'تخطي الآن',
        next: 'التالي',
        previos: 'السابق',
        accountSetting: 'إعداد الحساب',
        firstStep: 'الخطوة الاولى',
        secondStep: 'الخطوة الثانية',
        thirdStep: 'الخطوة الثالثة',
        finalStep: 'الخطوة الرابعة',
        basicInfo: 'المعلومات اللأساسية',
        studyAndCertificate: 'الدراسة و الشهادات',
        teachingSpecification: 'خصائص التدريس',
        availableTime: 'اللأوقات المتاحة',
        havingChallenges: 'هل تواجه تحديات ؟',
        contactUs: 'تواصل معنا لمساعدتك',
        bachelor: 'بكالريوس',
        diploma: 'دبلوم',
        certificate: 'الشهادة الجامعية',
        arabic: 'اللغة العربية',
        english: 'اللغة الإنجليزية',
        engineer: 'الهندسة',
        science: 'العلوم',
        physics: 'الفيزياء',
        algebra: 'الجبر',
        specialization: 'التخصص',
        experience: 'عدد سنوات الخبرة',
        fromOneToThreeYears: 'من 1 الى 3 سنوات',
        fromThreeToFiveYears: 'من 3 الى 5 سنوات',
        certificatesYouGot: 'الشهادات التي حصلت عليها',
        delete: 'حذف',
        certificateImg: 'صورة الشهادة',
        chooseFromDevice: 'اخيار من الجهاز',
        teachingTypes: 'انواع التدريس',
        remote: 'عن بعد',
        attend: 'حضوري',
        sr: 'ريال',
        hourPrice: 'سعر الساعة',
        makeOnZoom: 'يتم من على برنامج زوم',
        chooseAttendPlace: 'يتم تحديد المكان بالإتفاق',
        studentType: 'نوع الطلاب اللذين ترغب بالتدريس لهم',
        studentStage: 'المرحلة الدراسية للذين ترغب بالتدريس لهم',
        male: 'ذكر',
        female: 'أنثى',
        intermedate: 'متوسط',
        highschool: 'ثانوي',
        university: 'جامعي',
        search: 'البحث',
        subjectsYouTeach: 'المواد التعليمية التي تدرسها',
        arabic: "اللغة العربية",
        english: "اللغة الإنجليزية",
        engineer: "الهندسة",
        science: "العلوم",
        physics: "الفيزياء",
        math: "الجبر",
        reservationType: 'نوع الحجز',
        reservationByMassaging: 'حجز بالمراسلة',
        reservationBySchedule: 'حجز فوري',
        dateSelectionByMassaging: 'يتم تحديد الموعد من خلال تواصل الطلب معك بالدردشة',
        dateSelectionBySchedule: 'يختار الطلب موعد من التي تحدد انك متاح فيها على التقويم',
        personalSchedule: 'التقويم الخاص بك',
        edit: 'تعديل',
        saturday: 'السبت',
        sunday: 'الأحد',
        monday: 'الإثنين',
        tuesday: 'الثلاثاء',
        wednesday: 'الأربعاء',
        thursday: 'الخميس',
        friday: 'الجمعة',
        unavailable: 'غير متاح',
        am: 'ص',
        pm: 'م',
        to: 'الى',
        from: 'من',
        selectAvailableTime: 'حدد مدى توافرك',
        save: 'حفظ',
        thanksOrderRecieved: 'شكرا, تم إستلام طلبك',
        administrationWillContactYou: 'سوف تتواصل معك الإداره خلال 48 ساعه',
        accept: 'فهمت',
        close: 'إغلاق',
        main: 'الرئيسية',
        dates: 'المواعيد',
        massages: 'الرسائل',
        development: 'الدورات التطويرية',
        freeLessons: 'الدروس المجانية',
        savings: 'المحفظة و المجموعات',
        settings: 'الإعدادات',
        signout: 'تسجيل الخروج',
        signin: 'تسجيل الدخول',
        signup: 'حساب جديد',
        customAccount: 'تميز الحساب',
        totalBalance: 'الرصيد الكلي',
        moneyTransactions: 'المعاملات المالية',
        nextAppointment: 'الموعد القادم',
        minutes: 'دقائق',
        hours: 'ساعات',
        days: 'يوم',
        lessonLink: 'رابط الدرس',
        quickLinks: 'روابط سريعة',
        howYourFileShow: 'كيف يظهر ملفك للطلاب',
        inviteFriends: 'دعوة الأصدقاء',
        enterCode: 'ادخل كودالإحالة',
        technicalSupport: 'الدعم الفني واتس اب',
        dontHaveAccount: 'ليس لديك حساب؟',
        newAccount: 'حساب جديد',
        forgetPassword: 'نسيت كلمة المرور',
        phoneNumber: 'رقم الجوال',
        password: 'كلمة المرور',
        nameWarning: '* يجب ادخال الإسم',
        phoneWarning: '* استخدم تسعة ارقام فقط',
        emailWarning: '* تاكد من البريد الالكتروني',
        genderWarning: '* يجب التحديد من الخيارات',
        passwordWarning: '* استخدام 8 احرف او اكثر تحتوي على حرف كبير و صغير و رمز', 
        termsWarning: '* يجب الموافقه على الشروط و الأحكام',
        name: 'الإسم',
        email: 'البريد الإلكتروني',
        acceptTerms: 'الموافقة على ',
        men: 'ذكور',
        women: 'إناث',
        teachingHours: 'ساعات التدريس',
        studentsTeached: 'طلاب درست لهم',
        profileViews: 'مشاهدات ملفك',
        march: 'مارس',
        today: 'اليوم',
        weakly: 'أسبوعي',
        monthly: 'شهري',
        privateLesson: 'درس خصوصي',
        developmentCourse: 'دورة تطويرية',
        mohamedAbdullrabman: 'محمد عبدالرحمن',
        improveSearchEngines: 'تحسين محركات البحث',
        abdullrahmanKhatry: 'عبدالرحمن خطري',
        filter: 'التصفية',
        studentOneName: 'أحمد شوقي',
        studentTwoName: 'عبد الرحمن محمد',
        studentThreeName: 'مروة محمد عامر',
        studentFourName: 'مسفر الثبيتي',
        studentFiveName: 'عبد الماجد الخير',
        dateOne: 'الجمعه 30 ديسمبر 2022-09:00',
        dateTwo: 'الخميس 27 مايو 2022-12:15',
        dateThree: 'الاحد 12 ديسمبر 2022-04:30',
        dateFour: 'الجمعه 30 ديسمبر 2022-06:30',
        dateFive: 'الاثنين 19 ديسمبر 2022-10:00',
        coming: 'قادم',
        active: 'نشط',
        done: 'مكتمل',
        cancel: 'ملغي',
        dateDetails: 'تفاصيل الموعد',
        reservationDetails: 'تفاصيل الحجز',
        dateState: 'حالة الموعد',
        lessonDate: 'موعد الدرس',
        reservationHours: 'ساعات الحجز',
        lessonTime: 'مدة الدرس',
        lessonLocation: 'موقع الدرس',
        week: 'أسبوع',
        minute: 'دقيقة',
        reciept: 'الفاتورة',
        price: 'السعر',
        additionalVat: 'الضريبة المضافة',
        totalPrice: 'إجمالي السعر',
        massageStudent: 'مراسلة الطلب',
        apply: 'تطبيق',
        chating: 'المراسلة',
        selectDate: 'تحديد الموعد',
        send: 'إرسال',
        massageText: 'نص الرسالة',
        startMakingCourses: 'ابدأ في تقديم دورات في مختلف المجالات من خلال بث مباشر مع طلابك',
        addCourse: 'إضافة دورة',
        courseTime: 'وقت الدورة',
        courseLocation: 'موقع الدورة',
        startDate: 'موعد البدء',
        courseName: 'إسم الدورة',
        courseHours: 'عدد ساعات الدورة',
        topics: 'المواضيع',
        add: 'إضافة',
        shareCourse: 'نشر الدورة',
        suggestionsList:'قائمة اماكن مقترحة للدورة الحضوري',
        deleteLocation: 'حذف الموقع',
        yon: 'ينبع',
        tif: 'الطائف',  
        jedDiscription: 'جدة - الكورنيش',
        rydDiscription: 'الرياض - طريق الملك',
        yonDiscription: 'ينبع - المنتزه',
        tifDiscription: 'الطائف - الهدى',
        showOnMap: 'عرض على الخريطة',
        freeLessonsIncreaseYourExplore: 'الدروس المجانية تزيد من انتشارك و التعريف بك',
        addFreeLesson: 'إضافة درس مجاني',
        allowedNumber: 'العدد المسموح',
        reservedNumber: 'العدد المحجوز',
        student: 'طالب',
        lessonTopic: 'موضوع الدرس',
        maxStudent: 'اقصى عدد مسموح للحضور',
        addLesson: 'إضافة درس',
        lessonHour: 'وقت الدرس',
        shareLesson: 'نشر الدرس',
        transactionsEveryMonth: 'يتم تحويل مستحقاتك بداية كل شهر ميلادي تلقائيا',
        holdBalance: 'رصيد معلق',
        availableBalance: 'رصيد قابل للسحب',
        addBankAccount: 'أضف حساب بنكي لتحويل مستحقاتك',
        ifDontHaveAccount: 'إذا لم تمتلك حساب بنكي يمكن التواصل مع الإداره و تحديد الطريقه المناسبه لتحويل مستحقاتك',
        totalTransactions: 'إجمالي تعاملاتك داخل المنصة',
        usuallyTakesTwoDays: 'عادة تستغرق العملية الى ان تظهر في حسابك 48 ساعة',
        alahly: 'الأهلي',
        alrajhy: 'الراجحي',
        albalad: 'البلاد',
        alarabi: 'العربي',
        chooseBankName: 'إختر اسم البنك',
        transferToYou: 'تحويل لحسابك الشخصي',
        addAccountToRecieveSalary: 'ادخل معلومات الحساب البنكي الذي ترغب في استقبال مستحقاتك عليه',
        accountOwnerName: 'إسم صاحب البنك',
        accountNumber: 'رقم الحساب',
        ipanNumber: 'رقم الايبان',
    },
}

export default texts;